name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - main
      - rainfall
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - rainfall
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.8'
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure-static-web-apps-mango-mud-01760cc03: ${{ secrets.azure-static-web-apps-mango-mud-01760cc03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/"
          api_location: ""
          output_location: "build"
          app_build_command: "npm run build"
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure-static-web-apps-mango-mud-01760cc03: ${{ secrets.azure-static-web-apps-mango-mud-01760cc03 }}
          action: "close"
